apiVersion: v1
kind: Secret
metadata:
  name: pxc-secrets
  namespace: db-ha
type: Opaque
stringData:
  root: StrongRoot!123
  xtrabackup: StrongXBK!123
  monitor: StrongMon!123
  clustercheck: StrongChk!123
  proxyadmin: StrongPxy!123
  operator: StrongOp!123
  replication: StrongRepl!123
